[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sam_agent"
version = "0.1.0"
description = "Smart Administrative Messenger"

[tool.setuptools.packages.find]
where = ["src"]